export const exploreWorlds = [
  {
    id: "world-1",
    imgUrl: "/porkbelly.png",
    title: "Pork Belly",
    category: "Pork",
    text: "The part of the pork belly that is attached to the pork ribs. It is the most preferred pork part in Korea as it is delicious with its rich in fat.",
  },
  {
    id: "world-2",
    imgUrl: "/pigskin.png",
    title: "Pig Skin",
    category: "Pork",
    text: "It is a popular dish that is marinated with a savory sauce. When cooked over a grill, the skin becomes chewy and slightly crispy.",
  },
  {
    id: "world-3",
    imgUrl: "/thickporkbelly.png",
    title: "Thick Pork Belly",
    category: "Pork",
    text: "Same part as the pork belly but are cut thicker than the usual slices, allowing the meat to retain more of its natural fat and juiciness compared to thinner cuts.",
  },
  {
    id: "world-4",
    imgUrl: "/porkshoulder.png",
    title: "Pork Shoulder Butt",
    category: "Pork",
    text: "This is from the pork shoulder area, specifically the meat around the neck of the pig. It’s a flavorful cut with a good balance of lean meat and marbled fat, making it tender, juicy, and perfect for grilling.",
  },
  {
    id: "world-5",
    imgUrl: "/porkjowl.png",
    title: "Pork Jowl",
    category: "Pork",
    text: "A flavorful cut that comes from the pig’s cheek or jaw area. It has more marbling and slightly fattier than other parts of pork, marking it a unique chewy, sticky texture and incredibly juicy when cooked.",
  },
  {
    id: "world-6",
    imgUrl: "/slicedporkbelly.png",
    title: "Sliced Pork Belly",
    category: "Pork",
    text: "It is a popular cut of pork belly that is sliced thinly using a meat slicer because its crunch texture.",
  },
  {
    id: "world-7",
    imgUrl: "/marinatedpork.png",
    title: "Marinated Pork",
    category: ["Pork", "Marinated"],
    text: "A Korean pork dish prepared by seasoning the meat with various ingredients such as soy sauce, fish sauce, garlic, sugar, sesame oil, and black pepper. This dish is known for its rich flavor, where the sweet marinade blends perfectly with the pork, creating a deeply savory taste.",
  },
  {
    id: "world-8",
    imgUrl: "/soysaucechicken.png",
    title: "Soy Sauce Marinated Chicken",
    category: ["Chicken", "Marinated"],
    text: "Marinated in a soy sauce-based mixture, with garlic, sugar, sesame oil, and other seasonings. The result is a tender, juicy chicken with a perfect balance of savory, sweet, and umami flavors.",
  },
  {
    id: "world-9",
    imgUrl: "/sweetandspicychicken.png",
    title: "Sweet & Spicy Marinated Chicken",
    category: ["Chicken", "Marinated"],
    text: "Sweet and spicy marinated chicken is a delicious dish where chicken is coated in a marinade that combines both sweetness and spiciness. The result is a flavorful, tangy, and balanced dish that is perfect for those who enjoy bold flavors.",
  },
  {
    id: "world-10",
    imgUrl: "/shortplate.png",
    title: "Sliced Beef Short Plate",
    category: ["Beef"],
    text: "Cuts from the lower belly area of the cow. The beef belly generally contains a mixture of fatty layers and meat, offering a rich flavor and tenderness when cooked properly.",
  },
  {
    id: "world-11",
    imgUrl: "/brisket.png",
    title: "Sliced Beef Brisket",
    category: ["Beef"],
    text: "This refers to a specific cut from the chest area of the cow, just above the forelegs. It is a well-marbled cut with a lot of fat, which gives it a rich and tender texture when cooked.",
  },
  {
    id: "world-12",
    imgUrl: "/beefintestine.png",
    title: "Beef Intestine",
    category: ["Beef"],
    text: "It is a popular dish known for its chewy texture, rich flavor, and high collagen content.",
  },
  {
    id: "world-13",
    imgUrl: "/fingermeat.png",
    title: "Aged Finger Meat",
    category: ["Beef"],
    text: "A specific cut of beef that is located along the rib area of the cow, typically from the rib primal or short ribs. It is being loved with its unique chewy texture.",
  },
  {
    id: "world-14",
    imgUrl: "/beeftongue.png",
    title: "Beef Tongue",
    category: ["Beef"],
    text: "This is a unique cut of meat as it is tender yet slightly chewy, with a texture that differs from more common. When it is properly cooked, you can enjoy its tender, flavorful, and slightly chewy texture that sets it apart from other beef cuts",
  },
  {
    id: "world-15",
    imgUrl: "/labeef.png",
    title: "LA Style Beef Short Rib",
    category: ["Beef"],
    text: "LA beef short ribs are a thin-cut version of beef short ribs, typically sliced across the bone (flanken-style), giving it a rich, beefy flavor with a perfect balance of meat, fat, and bone.",
  },
  {
    id: "world-16",
    imgUrl: "/marinatedlabeef.png",
    title: "Marinated LA Style Beef Short Rib",
    category: ["Beef", "Marinated"],
    text: "Marinated LA beef short ribs are a flavorful dish made with short ribs that are marinated in a variety of seasonings before being cooked. This dish is popular for its rich, savory, and tender meat that is full of umami.",
  },
  {
    id: "world-17",
    imgUrl: "/beefchucktopblade.png",
    title: "Beef Chuck Top Blade",
    category: ["Beef"],
    text: "The beef chuck top blade comes from the chuck primal cut, specifically from the shoulder region of the cow. It is a well-marbled, flavorful cut but contains a tough connective tissue (the fascia) running through the center.",
  },
  {
    id: "world-18",
    imgUrl: "/beefbonelessrib.png",
    title: "Beef Boneless Rib",
    category: ["Beef"],
    text: "It comes from the short ribs section of the cow, and is one of the most popular cuts for grilling in Korea. This cut is prized for its tenderness, rich flavor, and marbling of fat, which gives a juicy and flavorful taste when grilled.",
  },
  {
    id: "world-19",
    imgUrl: "/beefchuckflap.png",
    title: "Beef Chuck Flap Tail",
    category: ["Beef"],
    text: "A specific cut of beef that comes from the chuck primal, which is located in the shoulder area of the cow, which is prized for its tenderness and marbling. It is chewier than boneless short rib.",
  },
  {
    id: "world-20",
    imgUrl: "/beefprimerib.png",
    title: "Prime Rib Eye Stake",
    category: ["Beef"],
    text: "Ribeye is a premium cut of beef from the rib section of the cow (usually from ribs 6 to 12). It’s known for its rich marbling (intramuscular fat), which makes it juicy, flavorful, and tender when cooked.",
  },
  {
    id: "world-21",
    imgUrl: "/assortedmushroom.png",
    title: "Assorted Mushroom",
    category: ["Side For Grill"],
    text: "---",
  },
  {
    id: "world-22",
    imgUrl: "/grillcheese.png",
    title: "Grill Cheese",
    category: ["Side For Grill"],
    text: "---",
  },
  {
    id: "world-23",
    imgUrl: "/squid.png",
    title: "Squid",
    category: ["Side For Grill"],
    text: "---",
  },
  {
    id: "world-24",
    imgUrl: "/tigershrimp.png",
    title: "Tiger Shrimp",
    category: ["Side For Grill"],
    text: "---",
  },
  {
    id: "world-25",
    imgUrl: "/vegancombo.png",
    title: "Vegan Combo",
    category: ["Side For Grill"],
    text: "---",
  },
  {
    id: "world-26",
    imgUrl: "/porkspicytofu.png",
    title: "Pork Spicy Tofu Stew",
    category: ["Soup and Hotpot"],
    text: "Spicy Tofu Soup is a traditional Korean soup made with soft tofu as the main ingredient. This dish is simple yet rich in flavor, characterized by the combination of spicy taste and the smooth texture of the soft tofu.",
  },
  {
    id: "world-27",
    imgUrl: "/fishcake.png",
    title: "Fish Cake Hot Pot",
    category: ["Soup and Hotpot"],
    text: "This is typically clear and light, made from a simple yet flavorful stock. It boasts a deep, savory taste, enhanced by the flavor released from the fish cakes.",
  },

  {
    id: "world-28",
    imgUrl: "/porkkimchi.png",
    title: "Pork Kimchi Hot Pot",
    category: ["Soup and Hotpot"],
    text: "Kimchi Stew is a popular Korean dish made with kimchi as the main ingredient, along with various seasonings, vegetables, tofu and pork. It’s a savory, spicy, and slightly tangy stew that's beloved in Korean cuisine.",
  },
  {
    id: "world-29",
    imgUrl: "/beefbroth.png",
    title: "Beef Broth Hot Pot",
    category: ["Soup and Hotpot"],
    text: "A traditional Korean stew which is a clear and rich soup made by simmering various parts of beef bone for a long time, resulting in a deep and mild flavor with various meats and vegetables. By adding various seasoning, the dish has a deeper and more savory taste.",
  },
  {
    id: "world-130",
    imgUrl: "/beeftendon.png",
    title: "Beef Tendon with Beef Broth",
    category: ["Soup and Hotpot"],
    text: "The broth of Sujee Jeongol is made by simmering the beef cartilage for a long time, resulting in a thick and flavorful stock. The distinct taste of beef and the collagen from the cartilage infuse into the broth, making it rich and savory.",
  },
  {
    id: "world-30",
    imgUrl: "/beefintestinehot.png",
    title: "Beef Intestines Hot Pot",
    category: ["Soup and Hotpot"],
    text: "A spicy and hearty stew made with beef intestines (gopchang), vegetables, and a flavorful broth. It is a popular dish in Korea, often enjoyed with rice or noodles.",
  },
  {
    id: "world-31",
    imgUrl: "/spicymixednoodle.png",
    title: "Spicy Mixed Noodles with Vegetables",
    category: ["Noodles"],
    text: "Bibim Guksu is a cold noodle dish mixed with a spicy sauce. It is typically made with wheat noodles and seasoned with a sauce that includes gochujang (Korean chili paste), vinegar, sugar, sesame oil, garlic, and other ingredients. Bibim Guksu is popular during the summer and is characterized by its refreshing, spicy, and tangy flavor.",
  },
  {
    id: "world-32",
    imgUrl: "/porksoup.png",
    title: "Pork Soup with Noodle",
    category: ["Noodles"],
    text: "This dish consists of a clear pork bone broth with wheat noodles, topped with boiled pork meat. It has a mild, savory flavor and is served with chili paste.",
  },
  {
    id: "world-33",
    imgUrl: "/kimchiudon.png",
    title: "Kimchi Udon",
    category: ["Noodles"],
    text: "Kimchi Udon is a Korean-style udon dish made by combining kimchi with udon noodles. The spicy and fermented flavor of the kimchi blends with the udon broth, providing a unique taste.",
  },
  {
    id: "world-34",
    imgUrl: "/coldnoodle.png",
    title: "Cold Noodle",
    category: ["Noodles"],
    text: "A famous Korean cold noodle dish made with buckwheat noodles(chewy texture). The noodles are served in a cold, tangy broth made from beef and the dish is typically garnished with vegetables and boiled egg. The broth has a cool, sweet, savory and slightly tangy flavor.",
  },
  {
    id: "world-35",
    imgUrl: "/coldnoodlewithoutsoup.png",
    title: "Cold Noodle",
    category: ["Noodles"],
    text: "A famous Korean cold noodle dish made with buckwheat noodles(chewy texture). The noodles are served in a cold, tangy broth made from beef and the dish is typically garnished with vegetables and boiled egg. The broth has a cool, sweet, savory and slightly tangy flavor.",
  },
  {
    id: "world-36",
    imgUrl: "/stirfriedglassnoodle.png",
    title: "Stir-Fried Glass Noodles",
    category: ["Noodles"],
    text: "A popular Korean dish made from stir-fried glass noodles , vegetables, and beef. The dish is known for its sweet, savory flavor, and chewy noodle texture that contrasts nicely with the vegetables and meat.",
  },
  {
    id: "world-37",
    imgUrl: "/steamedegg.png",
    title: "Steamed Egg",
    category: ["Side Dishes to share"],
    text: "This is made from whisked eggs, and various seasonings, then steamed until it reaches a smooth, fluffy, and custard-like texture. It's a simple, savory dish that's usually accompanying rice and other dishes",
  },
  {
    id: "world-38",
    imgUrl: "/spicyricecake.png",
    title: "Beef Brisket Spicy Rice Cake",
    category: ["Side Dishes to share"],
    text: "A variation of the classic Korean dish, which is a popular street food made with rice cakes and a spicy, sweet sauce. By adding sliced beef brisket to the traditional spicy rice cake, it is richer and heartier.",
  },
  {
    id: "world-39",
    imgUrl: "/greenonionpancake.png",
    title: "Korean beef Green Onion Pancake",
    category: ["Side Dishes to share"],
    text: "Korean Beef Pancake is a type of savory pancake made with beef and green onions, which are the main ingredients. It is a traditional Korean pancake dish, but with the addition of beef for extra flavor and richness.",
  },
  {
    id: "world-40",
    imgUrl: "/kimchipancake.png",
    title: "Kimchi Pancake with Bacon",
    category: ["Side Dishes to share"],
    text: "Kimchi Pancake with Bacon is a savory Korean pancake made primarily with kimchi and a simple batter of flour, water, and bacon. It's a popular dish in Korean cuisine, known for its tangy, spicy flavor and crispy texture.",
  },
  {
    id: "world-41",
    imgUrl: "/assortedkoreanpancake.png",
    title: "Assorted Korean Pancake",
    category: ["Side Dishes to share"],
    text: "A platter of assorted Korean-style savory pancakes, typically served as a side dish or appetizer, especially during special occasions, holidays, and Korean drinking gatherings.",
  },
  {
    id: "world-42",
    imgUrl: "/beeftartare.png",
    title: "Beef Tartare",
    category: ["Side Dishes to share"],
    text: "A traditional Korean dish made from raw beef that is julienned and typically served with a variety of seasonings and garnishes. It is often considered a delicacy and is known for its delicate, tender texture and the rich, savory flavors from the accompanying ingredients.",
  },
  {
    id: "world-43",
    imgUrl: "/spicystirfriedintestine.png",
    title: "Spicy Stir-fried Beef Intestine",
    category: ["Side Dishes to share"],
    text: "Spicy Stir-fried Vegetables with Beef Intestines is a Korean dish where beef intestines are stir-fried with a variety of vegetables in a spicy sauce. This version emphasizes a bolder, spicier flavor profile, combining the chewy texture of the beef intestines with a rich, spicy kick.",
  },
  {
    id: "world-44",
    imgUrl: "/spicybraised.png",
    title: "Spicy Braised Beef Tendon",
    category: ["Side Dishes to share"],
    text: "Spicy Braised Beef Tendon is a traditional Korean dish made by stewing beef cartilage with spicy seasonings. This dish is known for the harmony between the spicy flavor and the chewy meat.",
  },
  {
    id: "world-45",
    imgUrl: "/soybeanpasterice.png",
    title: "Soybean Paste Based Rice with Soup",
    category: ["Rice"],
    text: "A bibimbap-style dish made with thinly sliced beef brisket and soybean paste. The beef brisket is known for its high fat content, which enhances its deep, nutty aroma when combined with the salty and earthy taste of soybean paste, resulting in a flavorful and well-balanced dish.",
  },
  {
    id: "world-46",
    imgUrl: "/bibimbap.png",
    title: "Bibimbap",
    category: ["Rice"],
    text: "Bibimbap is a traditional Korean mixed rice dish that consists of various vegetables, meat, egg, and gochujang (Korean chili paste), known for its vibrant colors, well-balanced nutrition, and harmonious combination of flavors, making it one of Korea’s most iconic dishes.",
  },
];

export const startingFeatures = [
  "Find a world that suits you and you want to enter",
  "Enter the world by reading basmalah to be safe",
  "No need to beat around the bush, just stay on the gas and have fun",
];

export const newFeatures = [
  {
    imgUrl: "/vrpano.svg",
    title: "A new world",
    subtitle:
      "we have the latest update with new world for you to try never mind",
  },
  {
    imgUrl: "/headset.svg",
    title: "More realistic",
    subtitle:
      "In the latest update, your eyes are narrow, making the world more realistic than ever",
  },
];

export const insights = [
  {
    imgUrl: "/planet-06.png",
    title: "The launch of the Metaverse makes Elon musk ketar-ketir",
    subtitle:
      "Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Diam maecenas sed enim ut sem viverra alique.",
  },
  {
    imgUrl: "/planet-07.png",
    title: "7 tips to easily master the madness of the Metaverse",
    subtitle:
      "Vitae congue eu consequat ac felis donec. Et magnis dis parturient montes nascetur ridiculus mus. Convallis tellus id interdum",
  },
  {
    imgUrl: "/planet-08.png",
    title: "With one platform you can explore the whole world virtually",
    subtitle:
      "Quam quisque id diam vel quam elementum. Viverra nam libero justo laoreet sit amet cursus sit. Mauris in aliquam sem",
  },
];

export const socials = [
  {
    name: "twitter",
    url: "/twitter.svg",
  },
  {
    name: "linkedin",
    url: "/linkedin.svg",
  },
  {
    name: "instagram",
    url: "/instagram.svg",
  },
  {
    name: "facebook",
    url: "/facebook.svg",
  },
];
